export enum ServicesCatalog{
  NONE = "NONE",
  FLOOR_CLEANING = "FLOOR_CLEANING",
  RESIDENTIAL_CLEANING = "RESIDENTIAL_CLEANING",
  CAR_CLEANING = "CAR_CLEANING",
  OFFICE_CLEANING = "OFFICE_CLEANING",
  EXTERRIOR_CLEANING = "EXTERRIOR_CLEANING",
  POST_CONSTRUCTION_CLEANING = "POST_CONSTRUCTION_CLEANING",
  CARPET_CLEANING = "CARPET_CLEANING",
  LEATHER_CLEANING = "LEATHER_CLEANING",
  LEATHER_MAINTENANCE_RENOVATION = "LEATHER_MAINTENANCE_RENOVATION",
}
