export enum ServiceStatuses{
  PLANED = "PLANED",
SUCCESSFULLY_EXECUTED = "SUCCESSFULLY_EXECUTED",
CURRENTLY_EXECUTED = "CURRENTLY_EXECUTED",
EXECTUTED_WITH_PROBLEMS = "EXECTUTED_WITH_PROBLEMS",
REJECTED = "REJECTED",
CLOSED = "CLOSED",
}
